### PR TITLE
Finalized game saving + some more

### LINKED ISSUE #531: Savegames and tiles
This is more a reminder of what I'm planning to do for saving tiles. If you see something or want to comment, please feel free.

To remind the tile state for each player:
I would remove "claimed" from tile type (to avoid loosing the tile type when it is claimed). It would be replaced by a boolean (or by testing seat != nullptr && mClaimedPercentage>= 1.0).

To avoid showing gold tiles that have been digged somewhere you never had vision, I would display any gold tile (even with fullness = 0) as full gold tiles. That would also allow map creators to hide creatures within gold tiles (and having to had dirt tiles in the middle of gold tiles that makes too visible that there is something strange).

To allow to display room/traps after gamesave, in the room/trap definition, I would had the list of players that have seen this building. Moreover, rooms and traps would not be removed from gamemap when all their tiles are destroyed but also when no player have not refreshed vision since the building was destroyed (ie every human player did not see the room before it got destroyed or they got vision again after).

### LINKED ISSUE #560: Segfault with no helpful backtrace
Playing @Bertram25's current game, I experienced two segfaults so far, with unhelpful backtraces:

```
Computing turn 2118SERVER - Removing room Workshop36
> 20 loops in Creature::doUpkeep name:Troll96 seat id: 3. Breaking out..
SERVER - Removing rendered object RenderedMovableEntity_Crypt5_2418,MeshName=SmallSpider
signal 11 (Segmentation fault), address is 0x7fad14320af8 from 0x7fad14320af8

[bt]: (1) [0x7fad14320af8]
[bt]: (2) [0x7fad14320af8]

signal 11 (Segmentation fault), address is 0 from 0

[bt]: (1) [(nil)]
```

```
Computing turn 1664> 20 loops in Creature::doUpkeep name:Knight92 seat id: 0. Breaking out..
> 20 loops in Creature::doUpkeep name:Knight93 seat id: 0. Breaking out..
> 20 loops in Creature::doUpkeep name:Knight94 seat id: 0. Breaking out..
SERVER - Removing room Farm33
SERVER - Removing rendered object RenderedMovableEntity_Cannon_8_1298,MeshName=Cannonball
signal 11 (Segmentation fault), address is 0x7f7e7c0001c8 from 0x7f7e7c0001c8

[bt]: (1) [0x7f7e7c0001c8]
[bt]: (2) [0x7f7e7c0001c8]
```

I can't say if it's related to @Bertram25's current PR though, I hadn't played long games for a while, and my two segfaults appeared in mid game (turns 1664 and 2118).

### PR DESCRIPTION
**Pull request by hwoarangmy**
Sorry for this big (game breaker) PR but I had to mess with saving and repairing rooms (because they both need to know deleted tiles from building, they were tied).
Concerning game saving, basically, the server now reminds tile states for each human player (including building).
Moreover, buildings are removed from gamemap only when not used anymore (if a player sees an enemy building, looses vision and the building gets destroyed by someone else, the building will be removed from the gamemap only when the player will get vision again - and see it has been destroyed).

Building tiles are displayed at map load. Traps and just like persistent objects (dungeon temple and portal).

@oyvindln I've played a bit with memory. I tried to pay attention but if you could have a look with valgrind, it would be nice.

@akien-mga If nobody sees any obvious regression/problem with this PR, I propose we use my repo as it is right now for the next testing version

fixes #560 
fixes #531

### CODE REVIEW

File: source/entities/Building.cpp [hunk 1]
```diff
@@ -31,6 +32,57 @@ const Ogre::Vector3 SCALE(RenderManager::BLENDER_UNITS_PER_OGRE_UNIT,
         RenderManager::BLENDER_UNITS_PER_OGRE_UNIT,
         RenderManager::BLENDER_UNITS_PER_OGRE_UNIT);
 
+Building::~Building()
+{
+    for(std::pair<Tile* const, TileData*>& p : mTileData)
+    {
+        delete p.second;
+    }
+    mTileData.clear();
```
Comment (oyvindln) [inline source/entities/Building.cpp:41]: There is not really a need to call clear if the object is being destroyed anyway.

Comment (hwoarangmy) [inline source/entities/Building.cpp:41]: Yes, I agree. But I've done that everywhere else and I don't think it hurts too much, so...

**Comment by oyvindln** [comment]
Runs and compiles fine at least.

**Comment by akien-mga** [comment]
Building... I'm eager to test the beast! :-)
_Edit:_ That will be tomorrow ;-)

**Comment by akien-mga** [comment]
I'm seeing regressions with the treasury/gold sacks, but I need to debug it more to understand the issue. Apart from that this is looking quite fine, I'm letting a game run to see if the AI triggers segfaults, then I'll play a bit with the save/load functions.

**Comment by akien-mga** [comment]
No crash after 4782 turns in a game with three AI opponents, so I guess we're safe on that side :-)

**Comment by akien-mga** [comment]
I did three saves during my test game, I can load two of them but the first one I made gives me an error:

```
Asked to launch server with levelFilename=/home/akien/.local/share/opendungeons/saves/2015-03-21_113137-SK-ScreamInTheDark.level
Level Music: yd_Searching_ingame.ogg
Level Fight Music: The_Dark_Amulet.ogg

Adding goal KillAllEnemies
Adding goal ProtectDungeonTempleSERVER - Adding room Dormitory20, nbTiles=30, seatId=1
SERVER - Adding room Dormitory20, tile=[6,9]
SERVER - Adding room Dormitory20, tile=[7,9]
SERVER - Adding room Dormitory20, tile=[8,9]
SERVER - Adding room Dormitory20, tile=[9,9]
SERVER - Adding room Dormitory20, tile=[10,9]
SERVER - Adding room Dormitory20, tile=[11,9]
SERVER - Adding room Dormitory20, tile=[6,10]
SERVER - Adding room Dormitory20, tile=[7,10]
SERVER - Adding room Dormitory20, tile=[8,10]
SERVER - Adding room Dormitory20, tile=[9,10]
SERVER - Adding room Dormitory20, tile=[10,10]
SERVER - Adding room Dormitory20, tile=[11,10]
SERVER - Adding room Dormitory20, tile=[6,11]
SERVER - Adding room Dormitory20, tile=[7,11]
SERVER - Adding room Dormitory20, tile=[8,11]
SERVER - Adding room Dormitory20, tile=[11,11]
SERVER - Adding room Dormitory20, tile=[6,12]
SERVER - Adding room Dormitory20, tile=[7,12]
SERVER - Adding room Dormitory20, tile=[8,12]
SERVER - Adding room Dormitory20, tile=[6,13]
SERVER - Adding room Dormitory20, tile=[7,13]
SERVER - Adding room Dormitory20, tile=[8,13]
SERVER - Adding room Dormitory20, tile=[10,13]
SERVER - Adding room Dormitory20, tile=[11,13]
SERVER - Adding room Dormitory20, tile=[9,11]
SERVER - Adding room Dormitory20, tile=[9,12]
SERVER - Adding room Dormitory20, tile=[9,13]
SERVER - Adding room Dormitory20, tile=[10,11]
SERVER - Adding room Dormitory20, tile=[10,12]
SERVER - Adding room Dormitory20, tile=[11,12]
SERVER - Adding room DungeonTemple1, nbTiles=9, seatId=1
SERVER - Adding room DungeonTemple1, tile=[4,3]
SERVER - Adding room DungeonTemple1, tile=[4,4]
SERVER - Adding room DungeonTemple1, tile=[4,5]
SERVER - Adding room DungeonTemple1, tile=[5,3]
SERVER - Adding room DungeonTemple1, tile=[5,4]
SERVER - Adding room DungeonTemple1, tile=[5,5]
SERVER - Adding room DungeonTemple1, tile=[6,3]
SERVER - Adding room DungeonTemple1, tile=[6,4]
SERVER - Adding room DungeonTemple1, tile=[6,5]
SERVER - Adding room Farm22, nbTiles=21, seatId=1
SERVER - Adding room Farm22, tile=[5,8]
SERVER - Adding room Farm22, tile=[6,8]
SERVER - Adding room Farm22, tile=[7,8]
SERVER - Adding room Farm22, tile=[8,8]
SERVER - Adding room Farm22, tile=[9,8]
SERVER - Adding room Farm22, tile=[10,8]
SERVER - Adding room Farm22, tile=[11,8]
SERVER - Adding room Farm22, tile=[8,6]
SERVER - Adding room Farm22, tile=[8,7]
SERVER - Adding room Farm22, tile=[5,6]
SERVER - Adding room Farm22, tile=[5,7]
SERVER - Adding room Farm22, tile=[6,6]
SERVER - Adding room Farm22, tile=[6,7]
SERVER - Adding room Farm22, tile=[7,6]
SERVER - Adding room Farm22, tile=[7,7]
SERVER - Adding room Farm22, tile=[9,6]
SERVER - Adding room Farm22, tile=[9,7]
SERVER - Adding room Farm22, tile=[10,6]
SERVER - Adding room Farm22, tile=[10,7]
SERVER - Adding room Farm22, tile=[11,6]
SERVER - Adding room Farm22, tile=[11,7]
SERVER - Adding room Library21, nbTiles=25, seatId=1
SERVER - Adding room Library21, tile=[10,15]
SERVER - Adding room Library21, tile=[11,15]
SERVER - Adding room Library21, tile=[12,15]
SERVER - Adding room Library21, tile=[13,15]
SERVER - Adding room Library21, tile=[14,15]
SERVER - Adding room Library21, tile=[10,16]
SERVER - Adding room Library21, tile=[11,16]
SERVER - Adding room Library21, tile=[12,16]
SERVER - Adding room Library21, tile=[13,16]
SERVER - Adding room Library21, tile=[14,16]
SERVER - Adding room Library21, tile=[10,17]
SERVER - Adding room Library21, tile=[11,17]
SERVER - Adding room Library21, tile=[12,17]
SERVER - Adding room Library21, tile=[13,17]
SERVER - Adding room Library21, tile=[14,17]
SERVER - Adding room Library21, tile=[10,18]
SERVER - Adding room Library21, tile=[11,18]
SERVER - Adding room Library21, tile=[12,18]
SERVER - Adding room Library21, tile=[13,18]
SERVER - Adding room Library21, tile=[14,18]
SERVER - Adding room Library21, tile=[10,19]
SERVER - Adding room Library21, tile=[11,19]
SERVER - Adding room Library21, tile=[12,19]
SERVER - Adding room Library21, tile=[13,19]
SERVER - Adding room Library21, tile=[14,19]
SERVER - Adding room Portal2, nbTiles=9, seatId=1
SERVER - Adding room Portal2, tile=[4,18]
SERVER - Adding room Portal2, tile=[4,19]
SERVER - Adding room Portal2, tile=[4,20]
SERVER - Adding room Portal2, tile=[5,18]
SERVER - Adding room Portal2, tile=[5,19]
SERVER - Adding room Portal2, tile=[5,20]
SERVER - Adding room Portal2, tile=[6,18]
SERVER - Adding room Portal2, tile=[6,19]
SERVER - Adding room Portal2, tile=[6,20]
SERVER - Adding room Treasury19, nbTiles=5, seatId=1
SERVER - Adding room Treasury19, tile=[7,2]
SERVER - Adding room Treasury19, tile=[7,4]
SERVER - Adding room Treasury19, tile=[7,5]
SERVER - Adding room Treasury19, tile=[8,3]
SERVER - Adding room Treasury19, tile=[8,4]
Couldn't start server. The level file can't be loaded: /home/akien/.local/share/opendungeons/saves/2015-03-21_113137-SK-ScreamInTheDark.level
ERROR: Could not start server for single player game !!!
```

Apart from the actual issue that I haven't debugged yet, I think the log message is not really helpful: it sounds as if the file was _missing_ from the system, but the issue seems to be more that it doesn't manage to load the file because it's corrupted/the load system has a bug.

Here is the corresponding save file: http://remi.verschelde.fr/files/misc/2015-03-21_113137-SK-ScreamInTheDark.level
And here is a working save file from the same game, but 18 minutes later: http://remi.verschelde.fr/files/misc/2015-03-21_114931-SK-ScreamInTheDark.level

**Comment by akien-mga** [comment]
> And here is a working save file from the same game, but 18 minutes later: http://remi.verschelde.fr/files/misc/2015-03-21_114931-SK-ScreamInTheDark.level

I was a bit quick to say it's "working". I meant that the server can start and I can setup the seats, but then it segfaults when starting the game:

```
ERROR: Assert failed file /home/akien/Projects/opendungeons/OpenDungeons/source/rooms/RoomDormitory.cpp line 298 info : creatureName=Tentacle256
ERROR: Assert failed file /home/akien/Projects/opendungeons/OpenDungeons/source/rooms/RoomDormitory.cpp line 298 info : creatureName=Tentacle240
ERROR: Assert failed file /home/akien/Projects/opendungeons/OpenDungeons/source/rooms/RoomDormitory.cpp line 298 info : creatureName=Slime59
signal 11 (Segmentation fault), address is 0x20 from 0x5ba74a

[bt]: (1) ./opendungeons : RoomDormitory::createBed(Tile*, double, Creature*)+0x22a [0x5ba74a]
[bt]: (2) ./opendungeons : RoomDormitory::createBed(Tile*, double, Creature*)+0x22a [0x5ba74a]
[bt]: (3) ./opendungeons : RoomDormitory::restoreInitialEntityState()+0x7b [0x5baa6b]
[bt]: (4) ./opendungeons : GameMap::createAllEntities()+0x304 [0x4f49f4]
[bt]: (5) ./opendungeons : ODServer::serverThread()+0x204 [0x57f8c4]
[bt]: (6) /lib64/libsfml-system.so.2.2.0 : +0x9478 [0x7f9c348eb478]
[bt]: (7) /lib64/libpthread.so.0 : +0x75bd [0x7f9c330b85bd]
[bt]: (8) /lib64/libc.so.6 : clone+0x6d [0x7f9c33be05ed]
```

_Edit:_ Actually the save only produces a segfault if I tried loading the broken save (11:31:37) before.
Loading the 11:49:31 save after starting OD works just fine.

So I guess the server is not properly cleaned when a save can't be loaded as shown in the log in https://github.com/OpenDungeons/OpenDungeons/pull/563#issuecomment-84317981

**Comment by hwoarangmy** [comment]
> Loading the 11:49:31 save after starting OD works just fine.

Yes. FYI, I had already seen that the gamemap is not well cleaned when a level fails to load. But I didn't take time to look because it's minor IMHO since editor should not produce broken files. It should only happen when editing by hand levels.

**Comment by hwoarangmy** [comment]
> Here is the corresponding save file

I've had a look and it seems room Treasury19 is supposed to have 6 tiles but there are 7. Do you have the log from the game ? Or at least the replay ?

**Comment by hwoarangmy** [comment]
> No crash after 4782 turns in a game with three AI opponents, so I guess we're safe on that side :-)

I've also let something like 5 games run alone in the 2v2 skirmish test map and I got no segfault (I don't know turn number but I let it run until computer kills my dungeon).
I've also tried 1 multiplayer in the 4FFA small test map and no segfault either.

However, I've not played any real game since this PR (with active players other than AI)

**Comment by akien-mga** [comment]
> I've had a look and it seems room Treasury19 is supposed to have 6 tiles but there are 7. Do you have the log from the game ? Or at least the replay ?

I don't have the log anymore, hence my fix for #567 :-P

Here is the replay: http://remi.verschelde.fr/files/misc/replay_20150321_112424.odr
Note that the error you found seems to concur with the "treasury regressions" I was talking about. Basically I played the evil tester by creating and destroy treasury tiles with gold on them, and in the end my treasury was messed up with one tile having a gold sack that I could not pick even if I destroyed the treasury, and creating a treasury tile under this sack again would _decrease_ my gold count by like 5000 gold.

**Comment by oyvindln** [comment]
I'm also getting problems picking up gold stacks with this PR. I'm not sure exactly how it's supposed to function, but I couldn't pick up any gold.

**Comment by hwoarangmy** [comment]
> I'm also getting problems picking up gold stacks with this PR.

You cannot pickup gold in a treasury ATM. The only way is to sell a treasury tile with gold.

> Note that the error you found seems to concur with the "treasury regressions" as I was talking about.

I will try to play with treasuries to see if I can reproduce something. Anyway, in the "known issues", I already know that there will be some problems with game saving if a human player sees one of your room and you sell it. That's because in this case, it doesn't go to the "destroyed" tiles (I've not tested but IIRC, that's how it works and its perfectly untested). I will have a look closer as it might be related.

**Comment by hwoarangmy** [comment]
I'm currently having a look at the sold room tiles. I think it will change some things so no need to test too much this PR until my next commit

**Comment by hwoarangmy** [comment]
BTW, I've seen the reason why @akien-mga got an error on the tile numbers of rooms. It will also be fixed

**Comment by hwoarangmy** [comment]
Now, it should work even when selling rooms/traps

**Comment by akien-mga** [comment]
I got a segfault when adding a second treasury tile to my treasury:

```
Computing turn 222
During this turn there were 30 calls to GameMap::path().miscUpkeepTime=13023
Server sends newturn=222
Client received turnStarted=222
SERVER - Adding room Treasury2, nbTiles=1, seatId=1
SERVER - Adding room Treasury2, tile=[7,3]
SERVER - Room=Treasury2 is absorbing room=Treasury1

Computing turn 223
SERVER - Removing room Treasury1
During this turn there were 19 calls to GameMap::path().miscUpkeepTime=10293
signal 11 (Segmentation fault), address is 0x10 from 0x46bb4a

[bt]: (1) ./opendungeons : Building::notifySeatVision(Tile*, Seat*)+0x6a [0x46bb4a]
[bt]: (2) ./opendungeons : Building::notifySeatVision(Tile*, Seat*)+0x6a [0x46bb4a]
[bt]: (3) ./opendungeons : Seat::updateTileStateForSeat(Tile*)+0xce [0x4d3dbe]
[bt]: (4) ./opendungeons : Seat::notifyChangedVisibleTiles()+0x20d [0x4da05d]
[bt]: (5) ./opendungeons : GameMap::updateVisibleEntities()+0x8c [0x4ed70c]
[bt]: (6) ./opendungeons : ODServer::startNewTurn(double)+0x36f [0x58025f]
[bt]: (7) ./opendungeons : ODServer::serverThread()+0x276 [0x581586]
[bt]: (8) /lib64/libsfml-system.so.2.2.0 : +0x9478 [0x7f293fb56478]
[bt]: (9) /lib64/libpthread.so.0 : +0x75bd [0x7f293e3235bd]
[bt]: (10) /lib64/libc.so.6 : clone+0x6d [0x7f293ee4b5ed]

signal 11 (Segmentation fault), address is 0 from 0

[bt]: (1) [(nil)]
```

**Comment by hwoarangmy** [comment]
I've had a look and there is indeed a problem with room absorbtion. In reality, there is an architecture problem with them. We should consider absorbed rooms as if destroyed and absorbing rooms as if built over to make sure everything works if a player sees a room which gets absorbed while he has no vision.

**Comment by hwoarangmy** [comment]
@akien-mga This time, it should be fixed. If you are interested into testing deeper, the basic idea of room saving is that if an enemy human player sees a room, it won't get removed from gamemap if the room is destroyed until every human player that saw the room until it got destroyed see it again.
Thus, if you make a save game, the room should be in the list (but with tile hp = 0) and you should see the number of enemy human player with vision for each tile (followed by seat ids).
I've made some tests and checked that if no enemy human player had vision, the room is removed from gamemap when it is sold and if a human player gets vision, it's not.

**Comment by akien-mga** [comment]
I'm evil so I even tried destroying a treasury tile that was the target of a kobold bearing a gold stack, and after 2 seconds of frustrated wait, it seems the kobold managed to drag the gold someplace else :-p

And then to make it even more evil, I saved the game while a kobold was bearing gold back the treasury, and even while he was doing so and heading to a freshly destroyed treasury tile. After loading the saves, everything was still working fine. Great job! :-)

Now what's really needed would be to test saves in multiplayer with players having had sight on buildings/creatures.

As far as I am concerned, we can merge this one, create a dev snapshot and try some multiplayer games :-)

**Comment by hwoarangmy** [comment]
It is already possible to test multiplayer by launching 2 OD instances (host a game and join localhost). I've done that and, so far, I've seen no bug. But if you see interesting test scenario, please do not hesitate to tell.

**Comment by Bertram25** [comment]
Hey there, I've had a few single player games (especially the ones where you have several opponent and have to keep attacking/fleeing). And I haven't seen anything bad so far in regards of this PR.

I don't think I'll have the time to do a multiplayer this week but I'll gladly have a few games on friday evening if anybody wants some. :)

Can be merged IMHO if there is no other problems seen not fixed so far.

**Comment by Bertram25** [comment]
Ah and sorry for the late code review, I've been testing before reviewing the code actually. :P

**Comment by hwoarangmy** [comment]
> Ah and sorry for the late code review, I've been testing before reviewing the code actually. :P

That deserves a punishment. Something like a map full of BigKnights...

**Comment by Bertram25** [comment]
> That deserves a punishment. Something like a map full of BigKnights...

@Danimal696 !! I need some big creatures from the crypts!! Arg!

**Comment by akien-mga** [comment]
Let's merge the beast then :-)

**Comment by Bertram25** [comment]
Boom. Landed.

**Comment by hwoarangmy** [comment]
> @Danimal696 !! I need some big creatures from the crypts!! Arg!

You already have gnomes ! What are you complaining about ???

**Comment by Bertram25** [comment]
> You already have gnomes ! What are you complaining about ???

I'm afraid of gnomes in the dark... :S

**Comment by Danimal696** [comment]
They kick ass!!! really! they can take down creatures my orcs cant

**Comment by akien-mga** [comment]
@hwoarangmy If you want to make a Windows snapshot, I think now that this one has been merged would be a good time. So either a snapshot from OpenDungeons/development, or from your branch at fcb47b3.
I'll install my Mageia 4 VM in the meantime since I can't build the current master branch with the old gcc from Mageia 3.
