### PR TITLE
Fix resources being loaded twice + fix some issues reported by gcc sanitizer

### LINKED ISSUE #1271: Execution immediately failed with "Resource with the name MedievalSharp already exists" exception
OS: ubuntu 16.04
Source commit: 00de4b92af21127a312b23263a96722ae3e56aac
OGRE: 1.10 (custom build)
CEGUI: 0.8.7 (custom build)

Ogre.log: http://pastebin.com/raw/rwLSyBNi

### PR DESCRIPTION
**Pull request by oyvindln**
fixes #1271

Additional sanitizer complaints: 

```
/usr/local/include/OGRE/OgreSingleton.h:83:23: runtime error: downcast of address 0x7ffc83e19d60 which does not point to an object of type 'MusicPlayer'
0x7ffc83e19d60: note: object has invalid vptr
 60 61 00 00  00 00 00 00 00 00 00 00  64 cf 8d 5b 27 7f 00 00  80 c6 00 00 60 61 00 00  83 71 81 5b
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
/usr/local/include/OGRE/OgreSharedPtr.h:365:13: runtime error: member call on address 0x6030015343f0 which does not point to an object of type 'SharedPtrInfo'
0x6030015343f0: note: object is of type 'Ogre::SharedPtrInfoDeleteT<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >'
 c8 00 00 71  08 67 7c 5b 27 7f 00 00  00 00 00 00 be be be be  20 44 53 01 30 60 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Ogre::SharedPtrInfoDeleteT<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >'
/usr/local/include/OGRE/OgreSingleton.h:83:23: runtime error: downcast of address 0x7ffc83e19800 which does not point to an object of type 'SoundEffectsManager'
0x7ffc83e19800: note: object has invalid vptr
 fc 7f 00 00  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00  81 90 8b 5b 27 7f 00 00  81 61 81 5b
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
/usr/local/include/OGRE/OgreSingleton.h:83:23: runtime error: downcast of address 0x7ffc83e19ee0 which does not point to an object of type 'ODServer'
0x7ffc83e19ee0: note: object has invalid vptr
 60 60 00 00  00 00 00 00 00 00 00 00  f8 ff ff ff ff ff ff ff  00 70 94 5c 27 7f 00 00  c0 cb 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
/usr/local/include/OGRE/OgreSingleton.h:83:23: runtime error: downcast of address 0x7ffc83e1a9e0 which does not point to an object of type 'ODClient'
0x7ffc83e1a9e0: note: object has invalid vptr
 34 59 7a ff  00 00 00 00 00 00 00 00  30 b4 e1 83 fc 7f 00 00  30 ae e1 83 fc 7f 00 00  4e 35 7c 90
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
/usr/local/include/OGRE/OgreSingleton.h:83:23: runtime error: downcast of address 0x7ffc83e198e0 which does not point to an object of type 'ODFrameListener'
0x7ffc83e198e0: note: object has invalid vptr
 27 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  1a ad 79 5c
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
/<deleted>/OpenDungeons/source/gamemap/GameMap.cpp:124:14: runtime error: load of value 208, which is not a valid value for type 'bool'
/<deleted>/OpenDungeons/source/entities/MovableGameEntity.cpp:347:11: runtime error: load of value 190, which is not a valid value for type 'bool'
/<deleted>/OpenDungeons/source/creatureeffect/CreatureEffectSpeedChange.cpp:62:25: runtime error: member call on address 0x619000aab480 which does not point to an object of type 'Creature'
0x619000aab480: note: object is of type 'GameEntity'
 67 01 00 4b  c0 73 a7 35 0c 56 00 00  00 00 3c 42 ff 54 57 42  00 00 00 00 be be be be  a8 b4 aa 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'GameEntity'
/<deleted>/OpenDungeons/source/entities/Creature.cpp:654:12: runtime error: member access within address 0x619000aab480 which does not point to an object of type 'Creature'
0x619000aab480: note: object is of type 'GameEntity'
 67 01 00 4b  c0 73 a7 35 0c 56 00 00  00 00 3c 42 ff 54 57 42  00 00 00 00 be be be be  a8 b4 aa 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'GameEntity'
/<deleted>/OpenDungeons/source/creatureeffect/CreatureEffectSpeedChange.cpp:65:36: runtime error: member call on address 0x619000aab480 which does not point to an object of type 'Creature'
0x619000aab480: note: object is of type 'GameEntity'
 67 01 00 4b  c0 73 a7 35 0c 56 00 00  00 00 3c 42 ff 54 57 42  00 00 00 00 be be be be  a8 b4 aa 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'GameEntity'
/<deleted>/OpenDungeons/source/entities/Creature.cpp:3130:25: runtime error: member call on address 0x619000aab480 which does not point to an object of type 'Creature'
0x619000aab480: note: object is of type 'GameEntity'
 67 01 00 4b  c0 73 a7 35 0c 56 00 00  00 00 3c 42 ff 54 57 42  00 00 00 00 be be be be  a8 b4 aa 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'GameEntity'
/<deleted>/OpenDungeons/source/entities/Creature.cpp:3108:5: runtime error: member access within address 0x619000aab480 which does not point to an object of type 'Creature'
0x619000aab480: note: object is of type 'GameEntity'
 67 01 00 4b  c0 73 a7 35 0c 56 00 00  00 00 3c 42 ff 54 57 42  00 00 00 00 be be be be  a8 b4 aa 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'GameEntity'

=================================================================
==19151==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 672 byte(s) in 12 object(s) allocated from:
    #0 0x7f275b8b9270 in __interceptor_realloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7270)
    #1 0x7f2758ee7fd3  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x91fd3)

Direct leak of 448 byte(s) in 8 object(s) allocated from:
    #0 0x7f275b8b9f00 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7f00)
    #1 0x7f275a358954 in CEGUI::OgreTexture::loadFromMemory(void const*, CEGUI::Size<float> const&, CEGUI::Texture::PixelFormat) (/usr/local/lib/libCEGUIOgreRenderer-0.so.2+0x21954)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f275b8b8ec0 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc6ec0)
    #1 0x7f27543bbf4d in XextCreateExtension (/usr/lib/x86_64-linux-gnu/libXext.so.6+0xcf4d)

Indirect leak of 6184808 byte(s) in 8 object(s) allocated from:
    #0 0x7f275b8ba0a0 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc80a0)
    #1 0x7f275a35892f in CEGUI::OgreTexture::loadFromMemory(void const*, CEGUI::Size<float> const&, CEGUI::Texture::PixelFormat) (/usr/local/lib/libCEGUIOgreRenderer-0.so.2+0x2192f)

SUMMARY: AddressSanitizer: 6185952 byte(s) leaked in 29 allocation(s).
```

### CODE REVIEW

File: source/creatureeffect/CreatureEffectSpeedChange.cpp [hunk 1]
```diff
@@ -59,6 +59,7 @@ void CreatureEffectSpeedChange::applyEffect(Creature& creature)
 
 void CreatureEffectSpeedChange::releaseEffect(Creature& creature)
 {
+    //FIXME: sanitizer reports that this is called at least once on something that is not a creature.
```
Comment (hwoarangmy) [inline source/creatureeffect/CreatureEffectSpeedChange.cpp:62]: I don't believe this is called with something else than a creature. I would guess that somehow, we call this in the creature destructor and the object is not considered a creature anymore

Comment (oyvindln) [reply source/creatureeffect/CreatureEffectSpeedChange.cpp:62]: That sounds like it could be the issue yeah.

**Comment by hwoarangmy** [comment]
Nice tool, it seems to find some interesting stuff. It could be nice to somehow try to fix that (calling the creature effects when the creature is destroyed as we can suspect it can cause some problems ?). Maybe worth opening an issue ?

File: source/creatureeffect/CreatureEffectSpeedChange.cpp (hunk 1 above)
Comment (oyvindln) [reply source/creatureeffect/CreatureEffectSpeedChange.cpp:62]: In SpellCallToWar.cpp that happened in the opposite order, where a function was called in the constructor initializer list.

**Comment by oyvindln** [comment]
It makes it much easier to look for memory leaks at least as it's much much faster than valgrind and you can actually play with it enabled.

**Comment by hwoarangmy** [comment]
Interesting, thanks. I will have a look at this tool when I can.

**Comment by Bertram25** [comment]
Hey guys, I discovered sanitizer some time ago thanks to a colleague.
I guess this is something I should try to enable in debug mode.

File: source/creatureeffect/CreatureEffectSpeedChange.cpp (hunk 1 above)
Comment (Bertram25) [reply source/creatureeffect/CreatureEffectSpeedChange.cpp:62]: Btw, this is cool to see things being fixed, but is it a good idea to add fixme everywhere, even for things you know are false positives? Shouldn't this be an issue instead?

Comment (oyvindln) [reply source/creatureeffect/CreatureEffectSpeedChange.cpp:62]: Yeah should probably create an issue for stuff reported by the sanitizer. I'm not sure if I would call the issue false positives, as undefined behaviour can have unexpected effects.

**Comment by oyvindln** [comment]
So is this PR okay, or is there more I should do before merging?

**Comment by Bertram25** [comment]
@oyvindln IMHO, there is no issue with this PR, or at least none I could see so far. Let's merge.
